Laba4
orlovczeva-ekaterina/AQAcourse pull request #5
Opened 2024-01-21 18:21 UTC by orlovczeva-ekaterina

ПР по четвертой теме ООП

2024-01-23 20:44 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/1.kt
> +    var model: String = "Vlad"
логичнее свойства машинки делать через конструктор, иначе все машинки в стоке становятся одинаковыми... но при этом модель можно поменять сразу - представляешь едешь такой на гранте и бах на ролсе, трансформеры :)

2024-01-23 20:44 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/2.kt
> +    for (day in DayOfWeek.values())
если конструкция не в одну строку то обязательно в {} оборачивать
ифы там, фор итд

2024-01-23 20:44 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/5.kt
> +    var name: String = ""
раз делаются гет-сеттеры то переменную логично делать приватной, иначе смысл теряется

2024-02-04 17:04 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/2.kt
> +    for (day in DayOfWeek.values())
Но тут в одну строку

2024-02-04 18:26 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/2.kt
> +    for (day in DayOfWeek.values())
19 строка for
20 строка print

в одну строку это все на 19й строке

2024-02-05 05:48 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/1.kt
> +    var model: String = "Vlad"
исправила

2024-02-05 05:48 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/2.kt
> +    for (day in DayOfWeek.values())
исправила

2024-02-05 05:48 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/5.kt
> +    var name: String = ""
исправила

2024-02-05 07:34 UTC, vrnvorona approved these changes

2024-02-05 07:34 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/5.kt
> +    private var _name: String = ""
private модификатора достаточно, с _ обычно в kotlin не делают

2024-02-05 07:34 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/5.kt
> -            field = value
field более корректно т.к. внутри сеттера это прямая ссылка на поле

2024-02-25 19:52 UTC, vrnvorona approved these changes

2024-02-25 19:52 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/8.kt
> +class Circle(val pi: Double, val r: Double) : Shape() {
странно передавать pi снаружи

2024-02-25 19:52 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/9.kt
> +class Bird() : Flyable {
каждый класс должен наследоваться от обоих интерфейсов

2024-02-25 19:52 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/11.kt
> +fun executeOperation(operation: MathOperation, a: Double, b: Double): Double {
поч выбрала подход с внешней функцией а не методом класса и override?

2024-04-03 08:56 UTC, vrnvorona requested changes

2024-04-03 08:56 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/11.kt
> +    fun operation(op: MathOperation, a: Int, b: Int) = when (op) {
интересно, а нельзя ли это переделать в такой метод, чтобы не нужно было передавать op а он использовал self?

2024-04-03 08:56 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/12a.kt
> +class Playlist(){
```suggestion
}

class Playlist(){
```

2024-04-03 08:56 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/12a.kt
> +class Playlist(){
option+cmd+L почаще используй, код плохо отформатирован

2024-04-03 08:56 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/13a.kt
> +class OrderDI(val inventoryDI: InventoryDI){
тогда DI тоже надо делать с интерфейсом иначе ты привязываешься к конкретному классу

2024-04-03 08:56 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/14a.kt
> +class Warehouse1<T, K>(val name: T, val shipment: K) : Warehouses<T, K> {
логичнее иметь внутреннее хранилище и метод для добавления товара

а у тебя просто склад с 1 товаром который передается в конструкторе - т.е. не попадает на склад, а создается сразу со складом, странно

2024-04-03 08:56 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/laba4/8.kt
> +abstract class Sape() {
```suggestion
abstract class Shape() {
```

2024-04-10 17:58 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/11.kt
> +    fun operation(op: MathOperation, a: Int, b: Int) = when (op) {
В задании 11a я переписала эту же программу через оверрайд. То есть там не передается op в качестве параметра а абстрактный метод переопределяется в каждом объекте наследнике seald класса. 
Если ты про еще какой то способ то я не очень поняла. Ну или через функцию высшего порядка как в следующей лабе.

2024-04-10 17:58 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/12a.kt
> +class Playlist(){
исправила

2024-04-10 20:07 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/14a.kt
> +class Warehouse1<T, K>(val name: T, val shipment: K) : Warehouses<T, K> {
поправила

2024-04-10 20:07 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/laba4/13a.kt
> +class OrderDI(val inventoryDI: InventoryDI){
поправила

2024-04-11 07:14 UTC, vrnvorona approved these changes

2024-04-11 07:40 UTC, merged