Laba6
orlovczeva-ekaterina/AQAcourse pull request #7
Opened 2024-04-14 19:37 UTC by orlovczeva-ekaterina

Задания 6 лаба по null-safety

2024-04-16 14:45 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/Laba6/1.kt
> +    val a2: Int? = a?.length ?: 0
```suggestion
    val a2: Int? = a.length ?: 0
```

2024-04-16 14:46 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/Laba6/1.kt
> +    }
```suggestion
    if (a == null) {
        a3 = 0
    }
    a3 = a.length
```

2024-04-17 07:15 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/Laba6/3.kt
> +    s = s ?: "empty"
вообще такое использование var не очень хорошее т.к. читаемость может быть низкой. обычно var имеет смысл в каких то изменяемых состояниях в классе или может быть рядом с циклами какими-то. но переназначать переменную в голом поле странно. плюс тип у s Strin?, а после elvis станет String - теряем плюшки

2024-04-17 07:16 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/Laba6/5.kt
> +    fun mightThrowException() {
странно конечно, обычно в исключениях не пишут логику такую

обычно логика выбрасывает какое то исключение и все

2024-04-17 07:17 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/Laba6/5.kt
> +            throw Exception(message)
по факту ты сделала класс нового исключения, но кинула обычное Exception

если писать код внизу правильно catch (e: InvalidUserInputException) то он не поймает его

2024-04-17 07:17 UTC, vrnvorona requested changes
exception поправить бы

2024-04-22 08:46 UTC, vrnvorona commented on Laba1-0/src/main/kotlin/Laba6/3.kt
> +    val m: String? = s ?: "empty"
```suggestion
    val m: String = s ?: "empty"
```
но вообще можно не указывать

2024-04-22 08:46 UTC, vrnvorona approved these changes

2024-04-23 20:05 UTC, orlovczeva-ekaterina commented on Laba1-0/src/main/kotlin/Laba6/3.kt
> +    val m: String? = s ?: "empty"
Да. Вопрос в том нужен ли нам nullable m или нет. Ок, поправила

2024-04-23 20:07 UTC, merged